package:
  name: torcharrow
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    # - { { compiler('c') } } # [win]
    # - { { compiler('cxx') } } # [win]
    - cmake
    - python
    - boost
  host:
    - python
    - setuptools
    {{ environ.get('CONDA_PYTORCH_BUILD_CONSTRAINT') }}
  run:
    - python
    - numpy
    {% if osx %}
    - boost
    - libboost
    {% endif %}
    - typing_inspect
    - pandas
    - typing
    - tabulate
    - pyarrow
    - arrow
    - cffi
    - glog
    - gflags
    {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}

build:
  string: py{{py}}
  script_env:
    - BUILD_VERSION

#GitHub Actions usually provide Mac without AVX2 support, for now just skip the test until Velox can be run without AVX2
#pytest --no-header -v torcharrow/test
test:
  {% if linux %}
  imports:
    - torcharrow
  source_files:
    - torcharrow/test
  requires:
    - pytest
  {% endif %}

about:
  home: https://github.com/facebookresearch/torcharrow
  license: BSD
  license_file: LICENSE
  summary: "A torch.Tensor-like DataFrame library supporting multiple execution runtimes and Arrow as a common memory format."
  doc_url: https://github.com/facebookresearch/torcharrow/blob/main/tutorial/tutorial.ipynb
